# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choosedialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    business_checkboxes = []
    business_categories_checkboxes = []
    review_checkboxes = []
    tip_checkboxes = []
    user_checkboxes = []
    user_elite_checkboxes = []
    user_friends_checkboxes = []

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(714, 702)
        self.next = QtWidgets.QPushButton(Dialog)
        self.next.setGeometry(QtCore.QRect(560, 650, 113, 32))
        self.next.setObjectName("next")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(210, 10, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 610, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.yes_clean = QtWidgets.QRadioButton(Dialog)
        self.yes_clean.setGeometry(QtCore.QRect(440, 620, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.yes_clean.setFont(font)
        self.yes_clean.setObjectName("yes_clean")
        self.no_clean = QtWidgets.QRadioButton(Dialog)
        self.no_clean.setGeometry(QtCore.QRect(530, 620, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.no_clean.setFont(font)
        self.no_clean.setObjectName("no_clean")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(30, 70, 671, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.business = QtWidgets.QWidget()
        self.business.setObjectName("business")
        self.business_1 = QtWidgets.QCheckBox(self.business)
        self.business_1.setGeometry(QtCore.QRect(10, 10, 151, 21))
        self.business_1.setObjectName("business_1")
        self.business_2 = QtWidgets.QCheckBox(self.business)
        self.business_2.setGeometry(QtCore.QRect(10, 40, 87, 20))
        self.business_2.setObjectName("business_2")
        self.business_3 = QtWidgets.QCheckBox(self.business)
        self.business_3.setGeometry(QtCore.QRect(10, 70, 141, 21))
        self.business_3.setObjectName("business_3")
        self.business_4 = QtWidgets.QCheckBox(self.business)
        self.business_4.setGeometry(QtCore.QRect(10, 100, 87, 20))
        self.business_4.setObjectName("business_4")
        self.business_5 = QtWidgets.QCheckBox(self.business)
        self.business_5.setGeometry(QtCore.QRect(10, 130, 87, 20))
        self.business_5.setObjectName("business_5")
        self.business_6 = QtWidgets.QCheckBox(self.business)
        self.business_6.setGeometry(QtCore.QRect(10, 160, 87, 20))
        self.business_6.setObjectName("business_6")
        self.business_7 = QtWidgets.QCheckBox(self.business)
        self.business_7.setGeometry(QtCore.QRect(10, 190, 111, 20))
        self.business_7.setObjectName("business_7")
        self.business_8 = QtWidgets.QCheckBox(self.business)
        self.business_8.setGeometry(QtCore.QRect(10, 220, 87, 20))
        self.business_8.setObjectName("business_8")
        self.business_9 = QtWidgets.QCheckBox(self.business)
        self.business_9.setGeometry(QtCore.QRect(10, 250, 87, 20))
        self.business_9.setObjectName("business_9")
        self.business_10 = QtWidgets.QCheckBox(self.business)
        self.business_10.setGeometry(QtCore.QRect(10, 280, 121, 21))
        self.business_10.setObjectName("business_10")
        self.business_11 = QtWidgets.QCheckBox(self.business)
        self.business_11.setGeometry(QtCore.QRect(10, 310, 87, 20))
        self.business_11.setObjectName("business_11")
        self.tabWidget.addTab(self.business, "")
        self.business_categories = QtWidgets.QWidget()
        self.business_categories.setObjectName("business_categories")
        self.business_categories_1 = QtWidgets.QCheckBox(self.business_categories)
        self.business_categories_1.setGeometry(QtCore.QRect(10, 10, 87, 20))
        self.business_categories_1.setObjectName("business_categories_1")
        self.business_categories_2 = QtWidgets.QCheckBox(self.business_categories)
        self.business_categories_2.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.business_categories_2.setObjectName("business_categories_2")
        self.tabWidget.addTab(self.business_categories, "")
        self.review = QtWidgets.QWidget()
        self.review.setObjectName("review")
        self.review_1 = QtWidgets.QCheckBox(self.review)
        self.review_1.setGeometry(QtCore.QRect(10, 10, 87, 20))
        self.review_1.setObjectName("review_1")
        self.review_2 = QtWidgets.QCheckBox(self.review)
        self.review_2.setGeometry(QtCore.QRect(10, 40, 87, 20))
        self.review_2.setObjectName("review_2")
        self.review_3 = QtWidgets.QCheckBox(self.review)
        self.review_3.setGeometry(QtCore.QRect(10, 70, 151, 20))
        self.review_3.setObjectName("review_3")
        self.review_4 = QtWidgets.QCheckBox(self.review)
        self.review_4.setGeometry(QtCore.QRect(10, 100, 87, 20))
        self.review_4.setObjectName("review_4")
        self.review_5 = QtWidgets.QCheckBox(self.review)
        self.review_5.setGeometry(QtCore.QRect(10, 130, 87, 20))
        self.review_5.setObjectName("review_5")
        self.review_6 = QtWidgets.QCheckBox(self.review)
        self.review_6.setGeometry(QtCore.QRect(10, 160, 87, 20))
        self.review_6.setObjectName("review_6")
        self.review_7 = QtWidgets.QCheckBox(self.review)
        self.review_7.setGeometry(QtCore.QRect(10, 190, 87, 20))
        self.review_7.setObjectName("review_7")
        self.review_8 = QtWidgets.QCheckBox(self.review)
        self.review_8.setGeometry(QtCore.QRect(10, 220, 87, 20))
        self.review_8.setObjectName("review_8")
        self.review_9 = QtWidgets.QCheckBox(self.review)
        self.review_9.setGeometry(QtCore.QRect(10, 250, 87, 20))
        self.review_9.setObjectName("review_9")
        self.tabWidget.addTab(self.review, "")
        self.tip = QtWidgets.QWidget()
        self.tip.setObjectName("tip")
        self.tip_1 = QtWidgets.QCheckBox(self.tip)
        self.tip_1.setGeometry(QtCore.QRect(10, 10, 87, 20))
        self.tip_1.setObjectName("tip_1")
        self.tip_2 = QtWidgets.QCheckBox(self.tip)
        self.tip_2.setGeometry(QtCore.QRect(10, 40, 211, 20))
        self.tip_2.setObjectName("tip_2")
        self.tip_3 = QtWidgets.QCheckBox(self.tip)
        self.tip_3.setGeometry(QtCore.QRect(10, 70, 87, 20))
        self.tip_3.setObjectName("tip_3")
        self.tip_4 = QtWidgets.QCheckBox(self.tip)
        self.tip_4.setGeometry(QtCore.QRect(10, 100, 87, 20))
        self.tip_4.setObjectName("tip_4")
        self.tip_5 = QtWidgets.QCheckBox(self.tip)
        self.tip_5.setGeometry(QtCore.QRect(10, 130, 87, 20))
        self.tip_5.setObjectName("tip_5")
        self.tabWidget.addTab(self.tip, "")
        self.user = QtWidgets.QWidget()
        self.user.setObjectName("user")
        self.user_1 = QtWidgets.QCheckBox(self.user)
        self.user_1.setGeometry(QtCore.QRect(10, 10, 87, 20))
        self.user_1.setObjectName("user_1")
        self.user_2 = QtWidgets.QCheckBox(self.user)
        self.user_2.setGeometry(QtCore.QRect(10, 40, 87, 20))
        self.user_2.setObjectName("user_2")
        self.user_3 = QtWidgets.QCheckBox(self.user)
        self.user_3.setGeometry(QtCore.QRect(10, 70, 231, 20))
        self.user_3.setObjectName("user_3")
        self.user_4 = QtWidgets.QCheckBox(self.user)
        self.user_4.setGeometry(QtCore.QRect(10, 100, 231, 20))
        self.user_4.setObjectName("user_4")
        self.user_5 = QtWidgets.QCheckBox(self.user)
        self.user_5.setGeometry(QtCore.QRect(10, 130, 231, 20))
        self.user_5.setObjectName("user_5")
        self.user_6 = QtWidgets.QCheckBox(self.user)
        self.user_6.setGeometry(QtCore.QRect(10, 160, 231, 20))
        self.user_6.setObjectName("user_6")
        self.user_7 = QtWidgets.QCheckBox(self.user)
        self.user_7.setGeometry(QtCore.QRect(10, 190, 231, 20))
        self.user_7.setObjectName("user_7")
        self.user_8 = QtWidgets.QCheckBox(self.user)
        self.user_8.setGeometry(QtCore.QRect(10, 220, 231, 20))
        self.user_8.setObjectName("user_8")
        self.user_9 = QtWidgets.QCheckBox(self.user)
        self.user_9.setGeometry(QtCore.QRect(10, 250, 231, 20))
        self.user_9.setObjectName("user_9")
        self.user_10 = QtWidgets.QCheckBox(self.user)
        self.user_10.setGeometry(QtCore.QRect(10, 280, 231, 20))
        self.user_10.setObjectName("user_10")
        self.user_11 = QtWidgets.QCheckBox(self.user)
        self.user_11.setGeometry(QtCore.QRect(300, 10, 231, 20))
        self.user_11.setObjectName("user_11")
        self.user_12 = QtWidgets.QCheckBox(self.user)
        self.user_12.setGeometry(QtCore.QRect(300, 40, 231, 20))
        self.user_12.setObjectName("user_12")
        self.user_13 = QtWidgets.QCheckBox(self.user)
        self.user_13.setGeometry(QtCore.QRect(300, 70, 231, 20))
        self.user_13.setObjectName("user_13")
        self.user_14 = QtWidgets.QCheckBox(self.user)
        self.user_14.setGeometry(QtCore.QRect(300, 100, 231, 20))
        self.user_14.setObjectName("user_14")
        self.user_15 = QtWidgets.QCheckBox(self.user)
        self.user_15.setGeometry(QtCore.QRect(300, 130, 231, 20))
        self.user_15.setObjectName("user_15")
        self.user_16 = QtWidgets.QCheckBox(self.user)
        self.user_16.setGeometry(QtCore.QRect(300, 160, 231, 20))
        self.user_16.setObjectName("user_16")
        self.user_17 = QtWidgets.QCheckBox(self.user)
        self.user_17.setGeometry(QtCore.QRect(300, 190, 231, 20))
        self.user_17.setObjectName("user_17")
        self.user_18 = QtWidgets.QCheckBox(self.user)
        self.user_18.setGeometry(QtCore.QRect(300, 220, 231, 20))
        self.user_18.setObjectName("user_18")
        self.user_19 = QtWidgets.QCheckBox(self.user)
        self.user_19.setGeometry(QtCore.QRect(300, 250, 231, 20))
        self.user_19.setObjectName("user_19")
        self.user_20 = QtWidgets.QCheckBox(self.user)
        self.user_20.setGeometry(QtCore.QRect(300, 280, 231, 20))
        self.user_20.setObjectName("user_20")
        self.tabWidget.addTab(self.user, "")
        self.user_elite = QtWidgets.QWidget()
        self.user_elite.setObjectName("user_elite")
        self.user_elite_1 = QtWidgets.QCheckBox(self.user_elite)
        self.user_elite_1.setGeometry(QtCore.QRect(10, 10, 87, 20))
        self.user_elite_1.setObjectName("user_elite_1")
        self.user_elite_2 = QtWidgets.QCheckBox(self.user_elite)
        self.user_elite_2.setGeometry(QtCore.QRect(10, 40, 87, 20))
        self.user_elite_2.setObjectName("user_elite_2")
        self.tabWidget.addTab(self.user_elite, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.user_friends_1 = QtWidgets.QCheckBox(self.tab_8)
        self.user_friends_1.setGeometry(QtCore.QRect(10, 10, 87, 20))
        self.user_friends_1.setObjectName("user_friends_1")
        self.user_friends_2 = QtWidgets.QCheckBox(self.tab_8)
        self.user_friends_2.setGeometry(QtCore.QRect(10, 40, 87, 20))
        self.user_friends_2.setObjectName("user_friends_2")
        self.tabWidget.addTab(self.tab_8, "")
        self.restart = QtWidgets.QPushButton(Dialog)
        self.restart.setGeometry(QtCore.QRect(430, 650, 113, 32))
        self.restart.setObjectName("restart")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.next.setText(_translate("Dialog", "Next"))
        self.label.setText(_translate("Dialog", "Choose column you think important"))
        self.label_2.setText(_translate("Dialog", "Do you want to clean data you choose?"))
        self.yes_clean.setText(_translate("Dialog", "Yes"))
        self.no_clean.setText(_translate("Dialog", "No"))
        self.business_1.setText(_translate("Dialog", "business_id"))
        self.business_2.setText(_translate("Dialog", "name"))
        self.business_3.setText(_translate("Dialog", "neighborhood"))
        self.business_4.setText(_translate("Dialog", "address"))
        self.business_5.setText(_translate("Dialog", "city"))
        self.business_6.setText(_translate("Dialog", "state"))
        self.business_7.setText(_translate("Dialog", "postal_code"))
        self.business_8.setText(_translate("Dialog", "latitude"))
        self.business_9.setText(_translate("Dialog", "stars"))
        self.business_10.setText(_translate("Dialog", "review_count"))
        self.business_11.setText(_translate("Dialog", "is_open"))
        self.business_checkboxes.append(self.business_1)
        self.business_checkboxes.append(self.business_2)
        self.business_checkboxes.append(self.business_3)
        self.business_checkboxes.append(self.business_3)
        self.business_checkboxes.append(self.business_4)
        self.business_checkboxes.append(self.business_5)
        self.business_checkboxes.append(self.business_6)
        self.business_checkboxes.append(self.business_7)
        self.business_checkboxes.append(self.business_8)
        self.business_checkboxes.append(self.business_9)
        self.business_checkboxes.append(self.business_10)
        self.business_checkboxes.append(self.business_11)

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.business), _translate("Dialog", "business"))
        self.business_categories_1.setText(_translate("Dialog", "category"))
        self.business_categories_2.setText(_translate("Dialog", "business_id"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.business_categories), _translate("Dialog", "business_categories"))
        self.business_categories_checkboxes.append(self.business_categories_1)
        self.business_categories_checkboxes.append(self.business_categories_2)

        self.review_1.setText(_translate("Dialog", "review_id"))
        self.review_2.setText(_translate("Dialog", "user_id"))
        self.review_3.setText(_translate("Dialog", "business_id"))
        self.review_4.setText(_translate("Dialog", "stars"))
        self.review_5.setText(_translate("Dialog", "date"))
        self.review_6.setText(_translate("Dialog", "text"))
        self.review_7.setText(_translate("Dialog", "useful"))
        self.review_8.setText(_translate("Dialog", "funny"))
        self.review_9.setText(_translate("Dialog", "cool"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.review), _translate("Dialog", "review"))
        self.review_checkboxes.append(self.review_1)
        self.review_checkboxes.append(self.review_2)
        self.review_checkboxes.append(self.review_3)
        self.review_checkboxes.append(self.review_4)
        self.review_checkboxes.append(self.review_5)
        self.review_checkboxes.append(self.review_6)
        self.review_checkboxes.append(self.review_7)
        self.review_checkboxes.append(self.review_8)
        self.review_checkboxes.append(self.review_9)

        self.tip_1.setText(_translate("Dialog", "user_id"))
        self.tip_2.setText(_translate("Dialog", "business_id"))
        self.tip_3.setText(_translate("Dialog", "date"))
        self.tip_4.setText(_translate("Dialog", "text"))
        self.tip_5.setText(_translate("Dialog", "likes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tip), _translate("Dialog", "tip"))
        self.tip_checkboxes.append(self.tip_1)
        self.tip_checkboxes.append(self.tip_2)
        self.tip_checkboxes.append(self.tip_3)
        self.tip_checkboxes.append(self.tip_4)
        self.tip_checkboxes.append(self.tip_5)

        self.user_1.setText(_translate("Dialog", "user_id"))
        self.user_2.setText(_translate("Dialog", "name"))
        self.user_3.setText(_translate("Dialog", "review_count"))
        self.user_4.setText(_translate("Dialog", "average_stars"))
        self.user_5.setText(_translate("Dialog", "funny_vote_count"))
        self.user_6.setText(_translate("Dialog", "useful_vote_count"))
        self.user_7.setText(_translate("Dialog", "cool_vote_count"))
        self.user_8.setText(_translate("Dialog", "yelping_since"))
        self.user_9.setText(_translate("Dialog", "fans"))
        self.user_10.setText(_translate("Dialog", "compliment_plain"))
        self.user_11.setText(_translate("Dialog", "compliment_note"))
        self.user_12.setText(_translate("Dialog", "compliment_profile"))
        self.user_13.setText(_translate("Dialog", "compliment_writer"))
        self.user_14.setText(_translate("Dialog", "compliment_cute"))
        self.user_15.setText(_translate("Dialog", "compliment_cool"))
        self.user_16.setText(_translate("Dialog", "compliment_list"))
        self.user_17.setText(_translate("Dialog", "compliment_more"))
        self.user_18.setText(_translate("Dialog", "compliment_funny"))
        self.user_19.setText(_translate("Dialog", "compliment_hot"))
        self.user_20.setText(_translate("Dialog", "compliment_photos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.user), _translate("Dialog", "user"))
        self.user_checkboxes.append(self.user_1)
        self.user_checkboxes.append(self.user_2)
        self.user_checkboxes.append(self.user_3)
        self.user_checkboxes.append(self.user_4)
        self.user_checkboxes.append(self.user_5)
        self.user_checkboxes.append(self.user_6)
        self.user_checkboxes.append(self.user_7)
        self.user_checkboxes.append(self.user_8)
        self.user_checkboxes.append(self.user_9)
        self.user_checkboxes.append(self.user_10)
        self.user_checkboxes.append(self.user_11)
        self.user_checkboxes.append(self.user_12)
        self.user_checkboxes.append(self.user_13)
        self.user_checkboxes.append(self.user_14)
        self.user_checkboxes.append(self.user_15)
        self.user_checkboxes.append(self.user_16)
        self.user_checkboxes.append(self.user_17)
        self.user_checkboxes.append(self.user_18)
        self.user_checkboxes.append(self.user_19)
        self.user_checkboxes.append(self.user_20)

        self.user_elite_1.setText(_translate("Dialog", "user_id"))
        self.user_elite_2.setText(_translate("Dialog", "year"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.user_elite), _translate("Dialog", "user_elite"))
        self.user_elite_checkboxes.append(self.user_elite_1)
        self.user_elite_checkboxes.append(self.user_elite_2)

        self.user_friends_1.setText(_translate("Dialog", "user_id"))
        self.user_friends_2.setText(_translate("Dialog", "friend_id"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Dialog", "user_friends"))
        self.user_friends_checkboxes.append(self.user_friends_1)
        self.user_friends_checkboxes.append(self.user_friends_2)

        self.restart.setText(_translate("Dialog", "restart"))

